import type { TradeSignal, Position, NewsItem } from '@/lib/types/trading'

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString()
const minsAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000).toISOString()

export const mockSignals: TradeSignal[] = [
  {
    id: 'sig-001',
    symbol: 'RELIANCE',
    exchange: 'NSE',
    action: 'BUY',
    source: 'ai-technical',
    confidence: 87,
    entryPrice: 2892.50,
    targetPrice: 2980.00,
    stopLoss: 2845.00,
    quantity: 10,
    reasoning:
      'Strong bullish divergence on RSI with price forming higher lows. MACD crossover confirmed with increasing volume. Stock trading above 20-day EMA with support at 2845. Sector momentum positive with oil & gas index showing strength.',
    status: 'executed',
    pnl: 875.00,
    modelName: 'GLM-4-Plus',
    createdAt: hoursAgo(2),
    updatedAt: minsAgo(15),
  },
  {
    id: 'sig-002',
    symbol: 'TCS',
    exchange: 'NSE',
    action: 'SELL',
    source: 'ai-news',
    confidence: 72,
    entryPrice: 3845.00,
    targetPrice: 3720.00,
    stopLoss: 3890.00,
    quantity: 5,
    reasoning:
      'Negative sentiment detected in IT sector news. TCS reported lower-than-expected deal pipeline. Key support broken at 3850. Risk-reward favors short position.',
    status: 'pending',
    modelName: 'GLM-4-Plus',
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'sig-003',
    symbol: 'HDFCBANK',
    exchange: 'NSE',
    action: 'BUY',
    source: 'telegram',
    confidence: 65,
    entryPrice: 1678.25,
    targetPrice: 1740.00,
    stopLoss: 1645.00,
    quantity: 25,
    reasoning:
      'Banking sector showing recovery signals. HDFC Bank breaking out of consolidation zone. Strong institutional buying observed.',
    status: 'executed',
    pnl: 1543.75,
    channelId: '@stockproindia',
    createdAt: hoursAgo(4),
    updatedAt: minsAgo(30),
  },
  {
    id: 'sig-004',
    symbol: 'INFY',
    exchange: 'NSE',
    action: 'BUY',
    source: 'ai-technical',
    confidence: 91,
    entryPrice: 1562.30,
    targetPrice: 1620.00,
    stopLoss: 1535.00,
    quantity: 15,
    reasoning:
      'Cup and handle pattern completion on daily chart. Volume surge confirms breakout. IT sector rotation expected with strong global cues. AI analysis shows 91% confidence based on 47 similar historical patterns.',
    status: 'executed',
    pnl: 865.50,
    modelName: 'GLM-4-Long',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'sig-005',
    symbol: 'SBIN',
    exchange: 'NSE',
    action: 'SELL',
    source: 'telegram',
    confidence: 58,
    entryPrice: 812.40,
    targetPrice: 780.00,
    stopLoss: 835.00,
    quantity: 50,
    reasoning:
      'PSU banking sector facing headwinds. SBI NPA concerns resurfacing. Technical breakdown below key moving averages.',
    status: 'expired',
    channelId: '@niftytrader',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'sig-006',
    symbol: 'ICICIBANK',
    exchange: 'NSE',
    action: 'BUY',
    source: 'ai-news',
    confidence: 79,
    entryPrice: 1245.60,
    targetPrice: 1300.00,
    stopLoss: 1218.00,
    quantity: 20,
    reasoning:
      'Positive news flow: ICICI Bank reported highest-ever quarterly profit. Credit growth at 18% YoY. NIM expansion expected. News sentiment score: +0.82.',
    status: 'pending',
    modelName: 'GLM-4-Flash',
    createdAt: minsAgo(45),
    updatedAt: minsAgo(45),
  },
]

export const mockPositions: Position[] = [
  {
    id: 'pos-001',
    symbol: 'RELIANCE',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 10,
    entryPrice: 2892.50,
    currentPrice: 2980.00,
    pnl: 875.00,
    pnlPercent: 3.02,
    status: 'open',
    signalId: 'sig-001',
    createdAt: hoursAgo(2),
    updatedAt: minsAgo(15),
  },
  {
    id: 'pos-002',
    symbol: 'HDFCBANK',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 25,
    entryPrice: 1678.25,
    currentPrice: 1740.00,
    pnl: 1543.75,
    pnlPercent: 3.68,
    status: 'open',
    signalId: 'sig-003',
    createdAt: hoursAgo(4),
    updatedAt: minsAgo(30),
  },
  {
    id: 'pos-003',
    symbol: 'INFY',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 15,
    entryPrice: 1562.30,
    currentPrice: 1620.10,
    pnl: 866.90,
    pnlPercent: 3.70,
    status: 'open',
    signalId: 'sig-004',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'pos-004',
    symbol: 'TATAMOTORS',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 30,
    entryPrice: 978.50,
    currentPrice: 965.20,
    pnl: -399.00,
    pnlPercent: -1.36,
    status: 'open',
    createdAt: hoursAgo(5),
    updatedAt: minsAgo(10),
  },
]

export const mockClosedPositions: Position[] = [
  {
    id: 'pos-c01',
    symbol: 'WIPRO',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 40,
    entryPrice: 462.30,
    currentPrice: 478.50,
    pnl: 648.00,
    pnlPercent: 3.50,
    status: 'closed',
    closedAt: hoursAgo(12),
    createdAt: hoursAgo(36),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'pos-c02',
    symbol: 'ITC',
    exchange: 'NSE',
    action: 'BUY',
    quantity: 50,
    entryPrice: 438.75,
    currentPrice: 425.60,
    pnl: -657.50,
    pnlPercent: -3.00,
    status: 'closed',
    closedAt: hoursAgo(24),
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(24),
  },
  {
    id: 'pos-c03',
    symbol: 'BHARTIARTL',
    exchange: 'NSE',
    action: 'SELL',
    quantity: 15,
    entryPrice: 1520.00,
    currentPrice: 1485.30,
    pnl: 520.50,
    pnlPercent: 2.28,
    status: 'closed',
    closedAt: hoursAgo(18),
    createdAt: hoursAgo(42),
    updatedAt: hoursAgo(18),
  },
]

export const mockNews: NewsItem[] = [
  {
    id: 'news-001',
    title: 'RBI Holds Key Policy Rates Unchanged, Maintains Withdrawal of Accommodation',
    content:
      'The Reserve Bank of India kept the repo rate unchanged at 6.50% for the eighth consecutive meeting, while maintaining its stance of withdrawal of accommodation.',
    source: 'Economic Times',
    sentiment: 'positive',
    sentimentScore: 0.72,
    relatedSymbols: ['HDFCBANK', 'ICICIBANK', 'SBIN'],
    analyzed: true,
    aiSummary:
      'RBI rate hold is positive for banking stocks. Stable interest rate environment supports NIM stability for large banks. Expect continued momentum in banking sector.',
    publishedAt: hoursAgo(1),
    createdAt: hoursAgo(1),
  },
  {
    id: 'news-002',
    title: 'Reliance Industries Q4 Results Beat Estimates, Jio Adds 12M Subscribers',
    content:
      'Reliance Industries reported a 14% YoY jump in consolidated net profit, driven by strong performance in its digital services and retail businesses.',
    source: 'Moneycontrol',
    sentiment: 'positive',
    sentimentScore: 0.85,
    relatedSymbols: ['RELIANCE'],
    analyzed: true,
    aiSummary:
      'Strong quarterly results with Jio subscriber additions exceeding expectations. Retail business showing robust growth. Maintain positive outlook with target revision upward.',
    publishedAt: hoursAgo(3),
    createdAt: hoursAgo(3),
  },
  {
    id: 'news-003',
    title: 'IT Sector Faces Headwinds as Global Tech Spending Slows Down',
    content:
      'Indian IT companies may face challenges as global technology spending shows signs of deceleration amid economic uncertainty in key markets.',
    source: 'LiveMint',
    sentiment: 'negative',
    sentimentScore: -0.58,
    relatedSymbols: ['TCS', 'INFY', 'WIPRO'],
    analyzed: true,
    aiSummary:
      'Negative outlook for IT sector in near term. Global tech spending deceleration could impact deal pipelines. Short-term bearish bias recommended for IT stocks.',
    publishedAt: hoursAgo(5),
    createdAt: hoursAgo(5),
  },
  {
    id: 'news-004',
    title: 'Auto Sector Surges on Strong February Sales Data',
    content:
      'Automobile companies reported robust sales figures for February, with Maruti Suzuki and M&M posting double-digit growth in UV segment.',
    source: 'Business Standard',
    sentiment: 'positive',
    sentimentScore: 0.68,
    relatedSymbols: ['MARUTI', 'M&M', 'TATAMOTORS'],
    analyzed: true,
    aiSummary:
      'Auto sector showing strong demand momentum. UV segment outperforming expectations. Maruti and M&M are top picks based on volume growth trajectory.',
    publishedAt: hoursAgo(6),
    createdAt: hoursAgo(6),
  },
  {
    id: 'news-005',
    title: 'FII Outflows Continue for Third Consecutive Week, Drag Nifty Lower',
    content:
      'Foreign institutional investors pulled out over ₹8,500 crore from Indian equities this week, marking the third straight week of outflows.',
    source: 'NDTV Profit',
    sentiment: 'negative',
    sentimentScore: -0.45,
    relatedSymbols: [],
    analyzed: true,
    aiSummary:
      'Sustained FII selling pressure creating overhead supply. However, DII inflows providing support. Market may remain range-bound until FII trend reverses.',
    publishedAt: hoursAgo(8),
    createdAt: hoursAgo(8),
  },
  {
    id: 'news-006',
    title: 'ICICI Bank Reports Record Quarterly Profit, Credit Growth at 18% YoY',
    content:
      'ICICI Bank posted its highest-ever quarterly net profit of ₹11,053 crore, driven by strong credit growth and improved asset quality.',
    source: 'Financial Express',
    sentiment: 'positive',
    sentimentScore: 0.82,
    relatedSymbols: ['ICICIBANK'],
    analyzed: false,
    publishedAt: minsAgo(30),
    createdAt: minsAgo(30),
  },
]

export const watchlistData = [
  { symbol: 'RELIANCE', price: 2980.00, change: 87.50, changePercent: 3.02 },
  { symbol: 'TCS', price: 3812.50, change: -32.50, changePercent: -0.85 },
  { symbol: 'INFY', price: 1620.10, change: 57.80, changePercent: 3.70 },
  { symbol: 'HDFCBANK', price: 1740.00, change: 61.75, changePercent: 3.68 },
  { symbol: 'ICICIBANK', price: 1285.30, change: 39.70, changePercent: 3.19 },
  { symbol: 'SBIN', price: 805.60, change: -6.80, changePercent: -0.84 },
  { symbol: 'WIPRO', price: 478.50, change: 16.20, changePercent: 3.51 },
  { symbol: 'ITC', price: 432.80, change: -5.95, changePercent: -1.36 },
  { symbol: 'BHARTIARTL', price: 1498.75, change: 22.40, changePercent: 1.52 },
  { symbol: 'MARUTI', price: 12450.00, change: 345.00, changePercent: 2.85 },
]
